# /// script
# requires-python = ">=3.11"
# ///
"""Regenerate docs/ports.md from every stacks/*/compose.yaml.

    uv run scripts/ports.py

Run it after adding or changing a published port. The registry is how you pick
a free port for the next stack without grepping the whole tree.

Parsing is delegated to `docker compose config`, which already expands ranges,
splits protocols and normalizes long syntax. Hand-parsing the YAML gets all of
that subtly wrong -- most dangerously by reporting a dynamic port as a fixed
one.

The .env is deliberately NOT applied. This file is committed, and a port is
one of the things a host is entitled to override, so rendering with whichever
.env happened to be present records that machine and quietly disagrees with
every other one.
"""

import sys
from typing import NamedTuple

from compose import ROOT, STUB_FOR, stack_config, stack_dirs


class Mapping(NamedTuple):
    published: int
    target: int
    protocol: str
    host_ip: str | None
    label: str


def parse_ports(config):
    """Extract published port mappings from `docker compose config` JSON."""
    rows = []
    for service_name, service in (config.get("services") or {}).items():
        label = service.get("container_name", service_name)
        for port in service.get("ports", []):
            published = port.get("published")
            # No "published" key means Compose assigns a random host port at
            # run time. It reserves nothing, so it belongs in no registry.
            if published is None:
                continue
            rows.append(Mapping(
                int(published), int(port["target"]),
                port.get("protocol", "tcp"), port.get("host_ip"), label,
            ))
    return sorted(rows, key=lambda m: (m.published, m.label))


def render(rows, skipped=()):
    lines = ["# Ports", "",
             "Generated by `uv run scripts/ports.py`. Do not edit.", "",
             "These are the ports compose.yaml declares, rendered without any",
             "host's .env -- so this file is the same on every machine. A host",
             "may legitimately override one (a laptop cannot bind 80); ask",
             "`docker ps` what is actually bound there.", "",
             "Dynamic ports (a container port with no host port) are omitted:",
             "they reserve nothing.", "", "```"]
    for m in rows:
        # The stub stands in for the unset HOMELAB_HOST; printing 0.0.0.0 would
        # read as "every interface", the opposite of what the stack binds.
        host = "HOMELAB_HOST" if m.host_ip == STUB_FOR["HOMELAB_HOST"] else m.host_ip
        prefix = f"{host}:" if host else ""
        suffix = "" if m.protocol == "tcp" else f"/{m.protocol}"
        lines.append(f"{prefix}{m.published}:{m.target}{suffix} {m.label}")
    lines += ["```", ""]
    if skipped:
        # A stack whose compose cannot be interpolated here (a required env
        # var that only exists on the server) would otherwise vanish from
        # this file with no trace, and the file would look complete.
        lines += ["## Not represented above", "",
                  "These stacks could not be read on the machine that generated",
                  "this file, so their ports are missing -- not absent:", ""]
        lines += [f"- `{name}` -- {reason}" for name, reason in skipped]
        lines += [""]
    return "\n".join(lines)


if __name__ == "__main__":
    rows, skipped = [], []
    for stack_dir in stack_dirs():
        config = stack_config(stack_dir, declared_only=True)
        if config:
            rows.extend(parse_ports(config))
        else:
            skipped.append((stack_dir.name, "compose could not be interpolated"))
    rows.sort(key=lambda m: (m.published, m.label))

    collisions = {m.published for m in rows if
                  sum(1 for o in rows if o.published == m.published
                      and o.protocol == m.protocol) > 1}
    for port in sorted(collisions):
        print(f"  COLLISION on host port {port}", file=sys.stderr)

    (ROOT / "docs" / "ports.md").write_text(render(rows, skipped))
    print(f"wrote docs/ports.md, {len(rows)} mappings, "
          f"{len(skipped)} stack(s) skipped", file=sys.stderr)
