"""Every mandatory compose variable must appear in that stack's .env.example.

`${FOO:?msg}` in a compose file means the stack refuses to start without FOO.
.env.example is the only checked-in record of what to put in .env, so a
mandatory variable missing from it is a stack that cannot be brought up from
the repo alone -- and the failure lands on a fresh host, during a rebuild,
which is the worst time to discover it.

Found on 2026-09-03: stacks/caddy/compose.yaml had required PORKBUN_API_KEY
and PORKBUN_API_SECRET_KEY since that morning's wildcard-TLS work, and
.env.example still listed only CROWDSEC_API_KEY. Anyone following it got

    error while interpolating services.caddy.environment.[]:
    required variable PORKBUN_API_KEY is missing a value

The two files are edited in different commits by their nature -- one is
config, one is documentation -- so nothing but a check keeps them together.
"""
import re
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent))
from compose import stack_dirs

# ${VAR:?message} and ${VAR?message} both make VAR mandatory. ${VAR:-default}
# and ${VAR} do not, and must not be dragged in here: they are optional by
# construction and .env.example is free to leave them out.
MANDATORY = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*):?\?")


def required_vars(stack):
    return set(MANDATORY.findall((stack / "compose.yaml").read_text()))


# A commented-out entry counts as documented. That is not laxness -- some
# values must NOT ship a placeholder. authentik's AUTHENTIK_LDAP_TOKEN is
# written into .env by the provisioning script and never chosen by hand, so
# `# AUTHENTIK_LDAP_TOKEN=<generated>` is the correct way to record it and a
# live `AUTHENTIK_LDAP_TOKEN=CHANGEME` would be worse: it would start the
# stack with a token that authenticates nothing. What this test is really
# asking is whether a reader of .env.example learns the variable exists, not
# whether the file can be copied verbatim into a working .env.
DOCUMENTED = r"^\s*#?\s*{}\s*="


def documented_vars(stack, names):
    example = stack / ".env.example"
    if not example.exists():
        return None
    text = example.read_text()
    return {n for n in names
            if re.search(DOCUMENTED.format(re.escape(n)), text, re.MULTILINE)}


@pytest.mark.parametrize("stack", sorted(stack_dirs()), ids=lambda d: d.name)
def test_mandatory_vars_are_documented(stack):
    required = required_vars(stack)
    if not required:
        return
    documented = documented_vars(stack, required)
    assert documented is not None, (
        f"{stack.name}/compose.yaml requires {sorted(required)} but the stack "
        f"has no .env.example, so there is nothing to copy from")
    missing = required - documented
    assert not missing, (
        f"{stack.name}/compose.yaml requires {sorted(missing)} but "
        f".env.example does not mention them -- `docker compose up` fails on a "
        f"fresh checkout with 'required variable ... is missing a value'")


def test_the_check_can_actually_fail(tmp_path):
    """A parametrized test over real files passes vacuously if the regex breaks."""
    stack = tmp_path / "fake"
    stack.mkdir()
    (stack / "compose.yaml").write_text(
        "environment:\n"
        "  - NEEDED=${NEEDED:?set it}\n"
        "  - ALSO=${ALSO?set it}\n"          # no colon, still mandatory
        "  - OPTIONAL=${OPTIONAL:-default}\n"  # must NOT be required
        "  - PLAIN=${PLAIN}\n")
    (stack / ".env.example").write_text(
        "# a comment\n"
        "NEEDED=\n"
        "# ALSO=<generated by the provisioning step>\n")
    assert required_vars(stack) == {"NEEDED", "ALSO"}
    # Both forms count; UNSEEN is absent and would be the failure.
    assert documented_vars(stack, {"NEEDED", "ALSO", "UNSEEN"}) == {"NEEDED", "ALSO"}


# A guarded variable is enforced by `${VAR:?}`, which fails on unset OR empty.
# `CHANGEME` is neither, so it satisfies the guard and the stack starts on the
# placeholder. Found 2026-09-04 across 20 stacks, including ghostfolio's
# ACCESS_TOKEN_SALT and duplicati's SETTINGS_ENCRYPTION_KEY -- both on the
# "unrecoverable after first run" list in docs/lessons-learned.md §3.
#
# The invariant is inverted on purpose: a `:?` variable must be EMPTY unless it
# is named here. Hunting for placeholder strings instead was the first version
# of this test and it was weak in two directions -- `CHANGEME` in quotes or
# followed by a comment slipped past the regex, and `TODO`, `xxx` or
# `your-key-here` were never checked at all. "Empty unless allowlisted" cannot
# be evaded by spelling.
#
# The cost is that a new stack with a real default has to add a line below.
# That is the point: the line records why shipping a value there is safe.
#
# The EXACT value is pinned, not just the variable name. Naming only the
# variable allowed the exception to cover any future value: with an earlier
# version of this table, editing the allowlisted HA_URL to `CHANGEME` passed
# the whole suite. An allowlist that does not say what is allowed is a hole
# with a comment on it.
ALLOWED_DEFAULTS = {
    # (stack, variable): (the exact value, why it is correct despite the guard)
}

# `${VAR?}` (no colon) fails only on UNSET, so empty satisfies it and this
# test's advice would be wrong for it. No stack uses that form; required_vars()
# accepts both because the documentation half applies to both.
GUARDED = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*):\?")

# Matches an assignment with anything after the `=`, quoted or trailed by a
# comment. `VAR=` and `# VAR=...` are the two forms that must NOT match.
#
# Horizontal whitespace only, never `\s`: `\s*` after the `=` happily consumes
# the newline and matches the NEXT line's assignment, so every empty variable
# reads as holding whatever is declared below it. That is not a hypothetical --
# it is what the first version of this file did, and it failed 13 stacks
# claiming NEXTAUTH_SECRET was set to the literal text "MEILI_MASTER_KEY=".
HORIZONTAL_WS = r"[^\S\n]*"
VALUED_ENV_ASSIGNMENT = (
    rf"^{HORIZONTAL_WS}{{}}{HORIZONTAL_WS}={HORIZONTAL_WS}"
    rf"(\S.*?){HORIZONTAL_WS}$")


def guarded_vars(stack):
    return set(GUARDED.findall((stack / "compose.yaml").read_text()))


def valued_vars(stack, names):
    """Guarded variables that .env.example gives any value at all."""
    text = (stack / ".env.example").read_text()
    found = {}
    for n in names:
        m = re.search(VALUED_ENV_ASSIGNMENT.format(re.escape(n)),
                      text, re.MULTILINE)
        if m:
            found[n] = m.group(1)
    return found


@pytest.mark.parametrize("stack", sorted(stack_dirs()), ids=lambda d: d.name)
def test_guarded_vars_are_empty_unless_allowlisted(stack):
    if not (stack / ".env.example").exists():
        return
    for name, value in valued_vars(stack, guarded_vars(stack)).items():
        entry = ALLOWED_DEFAULTS.get((stack.name, name))
        assert entry is not None, (
            f"{stack.name}/.env.example gives {name} the value {value!r}, but "
            f"compose.yaml guards it with `:?` -- which fails only on unset or "
            f"EMPTY. Any value satisfies the guard, so a placeholder starts "
            f"the stack on itself. Leave it empty, or add it to "
            f"ALLOWED_DEFAULTS here with the reason it is a real default. "
            f"See docs/lessons-learned.md §3")
        expected, reason = entry
        assert value == expected, (
            f"{stack.name}/.env.example sets {name} to {value!r}, but "
            f"ALLOWED_DEFAULTS permits only {expected!r} ({reason}). The "
            f"exception is for that value, not for the variable -- update the "
            f"allowlist deliberately if the default really changed")


def test_allowlist_has_no_stale_entries():
    """An entry that outlives the value it was written for silently permits
    whatever is put there next. Keyed on VALUED, not merely guarded: a variable
    that goes back to empty no longer needs an exception, and leaving one
    behind re-opens the hole the moment someone fills it in again."""
    live = {(d.name, n)
            for d in stack_dirs() if (d / ".env.example").exists()
            for n in valued_vars(d, guarded_vars(d))}
    stale = set(ALLOWED_DEFAULTS) - live
    assert not stale, (
        f"ALLOWED_DEFAULTS holds entries for {sorted(stale)}, which are no "
        f"longer guarded variables carrying a value. Delete them")


def test_the_empty_check_catches_what_a_placeholder_scan_missed(tmp_path):
    """The three evasions that killed the string-matching version."""
    stack = tmp_path / "fake"
    stack.mkdir()
    (stack / "compose.yaml").write_text(
        "environment:\n"
        "  - BARE=${BARE:?}\n"
        "  - QUOTED=${QUOTED:?}\n"
        "  - TRAILING=${TRAILING:?}\n"
        "  - NOVEL=${NOVEL:?}\n"
        "  - FINE=${FINE:?}\n"
        "  - WEAK=${WEAK?}\n")
    (stack / ".env.example").write_text(
        "BARE=CHANGEME\n"
        'QUOTED="CHANGEME"\n'
        "TRAILING=CHANGEME  # fill me in\n"
        "NOVEL=your-key-here\n"
        "FINE=\n"
        "WEAK=whatever\n")
    assert guarded_vars(stack) == {"BARE", "QUOTED", "TRAILING", "NOVEL", "FINE"}, \
        "the no-colon ${WEAK?} form must not be held to the empty rule"
    assert set(valued_vars(stack, guarded_vars(stack))) == {
        "BARE", "QUOTED", "TRAILING", "NOVEL"}


# An image tag pinned in .env.example is a pin that lives in a gitignored file.
# Compose writes `image: repo:${VAR:-default}` so that one variable can drive
# several services -- authentik needs server, worker and ldap on one tag or the
# outpost silently stops matching the instance -- and the committed default is
# then the repo's record of what runs. Shipping the same variable in
# .env.example puts a SECOND pin on every host, in the file that wins, and
# `git grep` reports the version that lost.
#
# Found 2026-09-04 in three stacks. authentik was the proof: compose.yaml said
# 2026.8.0, the laptop's .env said 2026.5.6, and the first server ran what its own .env
# said. Bumping the committed default upgraded nothing anywhere.
#
# Overriding for a one-off test is still fine -- `VAR=x docker compose up -d`
# passes through the environment. What must not happen is persisting it.
IMAGE_VAR = re.compile(
    r"^\s*image:.*\$\{([A-Za-z_][A-Za-z0-9_]*)", re.MULTILINE)


def image_vars(stack):
    return set(IMAGE_VAR.findall((stack / "compose.yaml").read_text()))


@pytest.mark.parametrize("stack", sorted(stack_dirs()), ids=lambda d: d.name)
def test_image_tags_are_not_pinned_in_env_example(stack):
    if not (stack / ".env.example").exists():
        return
    for name, value in valued_vars(stack, image_vars(stack)).items():
        raise AssertionError(
            f"{stack.name}/.env.example sets {name}={value}, but compose.yaml "
            f"uses it as an image tag. .env is gitignored and wins over the "
            f"committed default, so the repo would record one version while "
            f"the host runs another. Delete the line; the pin belongs in "
            f"compose.yaml")


def test_the_image_pin_check_can_fail(tmp_path):
    """Proves the regex reaches an image line and ignores a commented pin."""
    stack = tmp_path / "fake"
    stack.mkdir()
    (stack / "compose.yaml").write_text(
        "services:\n"
        "  a:\n"
        "    image: ghcr.io/x/a:${A_TAG:-1.0}\n"
        "  b:\n"
        "    image: ghcr.io/x/b:${A_TAG:-1.0}\n"        # one var, two services
        "  c:\n"
        "    image: plain/c:2.0\n"                      # no variable at all
        "    environment:\n"
        "      - NOT_AN_IMAGE=${OTHER:-x}\n")           # not on an image line
    (stack / ".env.example").write_text(
        "A_TAG=1.0\n"
        "# B_TAG=1.0\n"
        "OTHER=x\n")
    assert image_vars(stack) == {"A_TAG"}, \
        "only variables used on an `image:` line count"
    assert valued_vars(stack, image_vars(stack)) == {"A_TAG": "1.0"}
    # Commented out is not a pin, and neither is absent.
    (stack / ".env.example").write_text("# A_TAG=1.0\n")
    assert valued_vars(stack, image_vars(stack)) == {}
